name: venue_user
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.2.0
  page_transition: ^2.0.5
  flutter_screenutil: ^5.2.0
  http: ^0.13.4
  simple_gradient_text: ^1.2.2
  otp_text_field: ^1.1.2
  easy_gradient_text: ^1.0.0
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  flutter_calendar_carousel: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  simple_animations: ^1.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/launchericon/launcher.png"
flutter:

  uses-material-design: true
  assets:
    - assets/splashimage/
    - assets/icon/
    - assets/properties/
    - assets/icon/eventcard/
    - assets/icon/sign/
    - assets/icon/bottomicon/
    - assets/icon/person/
    - assets/mainpage/
    - assets/mainpage/image/
  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/Questrial-Regular.ttf
